apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: nextapp
  app.kubernetes.io/instance: nextapp
  app.kubernetes.io/name: nextapp